# Generated by Django 3.2.6 on 2021-11-19 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vistaraapp', '0003_rename_video_comment_vid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='vid',
            new_name='video',
        ),
    ]
