# Generated by Django 3.2.6 on 2021-11-19 03:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vistaraapp', '0004_rename_vid_comment_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='video',
            new_name='videoes',
        ),
    ]
